apiVersion: v2
name: identity-service
description: A Helm chart for the Go identity service serving the auth, users and roles operations
type: application
version: 0.1.0
appVersion: "0.0.2"
dependencies:
  - name: common
    version: 0.5.0
    repository: file://../common
