apiVersion: v2
name: rolesui
description: A Helm chart for Kubernetes
type: application
version: 0.6.0
appVersion: "1.0.25"
dependencies:
  - name: common
    version: 0.5.0
    repository: file://../common
