image:
  tag: "1.0.14@sha256:d352e9997ea64ad370e60c4db91a36b3be00929029a8f5b52e0d33b932c27208"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "160Mi"
    cpu: "500m"

ingress:
  hosts:
    - host: rolesui.prd.jdwlabs.com

envs:
  ENVIRONMENT: prod
  AUTH_BASE_URL: https://usersrole.prd.jdwlabs.com