image:
  tag: "1.0.25@sha256:fdc27507de33ec9e4c0802020cdf7399331697e001dedfb17b7c3f98b12ffbfc"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "160Mi"
    cpu: "500m"

ingress:
  hosts:
    - host: rolesui.prd.jdwlabs.com

envs:
  ENVIRONMENT: prod
  AUTH_BASE_URL: https://usersrole.prd.jdwlabs.com