image:
  tag: "1.0.11@sha256:008e6727b26ea99ca61af74ab78f04e32e78dccae4ac42f3be0a0fc3ed80d0f4"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

ingress:
  hosts:
    - host: rolesui.prd.jdwlabs.com

envs:
  ENVIRONMENT: prod
  AUTH_BASE_URL: https://usersrole.prd.jdwlabs.com