apps:
  # --- NON environment ---
  - name: secret-store-non
    namespace: jdwlabs-non
    chartPath: charts/secret-store
    syncWave: "0"
    valueFiles:
      - values.yaml
      - values-non.yaml

  - name: usersrole-non
    namespace: jdwlabs-non
    chartPath: charts/usersrole
    syncWave: "1"
    valueFiles:
      - values.yaml
      - values-non.yaml

  - name: servicediscovery-non
    namespace: jdwlabs-non
    chartPath: charts/servicediscovery
    syncWave: "1"
    valueFiles:
      - values.yaml
      - values-non.yaml

  - name: container-non
    namespace: jdwlabs-non
    chartPath: charts/container
    syncWave: "1"
    valueFiles:
      - values.yaml
      - values-non.yaml

  - name: authui-non
    namespace: jdwlabs-non
    chartPath: charts/authui
    syncWave: "1"
    valueFiles:
      - values.yaml
      - values-non.yaml

  - name: usersui-non
    namespace: jdwlabs-non
    chartPath: charts/usersui
    syncWave: "1"
    valueFiles:
      - values.yaml
      - values-non.yaml

  - name: rolesui-non
    namespace: jdwlabs-non
    chartPath: charts/rolesui
    syncWave: "1"
    valueFiles:
      - values.yaml
      - values-non.yaml
