image:
  tag: "2.0.5@sha256:6fa3e33f301b485947b7d0979321df5ab3c78dcfc904844dea11ed3902faa3a7"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

ingress:
  hosts:
    - host: authui.prd.jdwlabs.com

envs:
  ENVIRONMENT: prod
  AUTH_BASE_URL: https://usersrole.prd.jdwlabs.com