image:
  tag: "2.0.14@sha256:aeb45bef2fd9e906cf9023eadb12181cec30366c0d738c3b66490c39cfb09baf"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

ingress:
  hosts:
    - host: authui.prd.jdwlabs.com

envs:
  ENVIRONMENT: prod
  AUTH_BASE_URL: https://usersrole.prd.jdwlabs.com