revisionHistoryLimit: 1

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: authui.non.jdwlabs.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - authui.non.jdwlabs.com
      secretName: authui-non-tls

envs:
  ENVIRONMENT: non
  AUTH_BASE_URL: https://usersrole.non.jdwlabs.com