image:
  tag: "2.0.27@sha256:4b4626668a41145ba312783ef970c32262be7a0a4cae85e7011d667ee7f12c5d"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "160Mi"
    cpu: "500m"

ingress:
  hosts:
    - host: authui.prd.jdwlabs.com

envs:
  ENVIRONMENT: prod
  AUTH_BASE_URL: https://usersrole.prd.jdwlabs.com