image:
  tag: "2.1.21@sha256:ff114649f5800ba0ce1bb1011c5911a6f8b96e7b512d9e0bf86b93176e3dbf35"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "160Mi"
    cpu: "500m"

ingress:
  hosts:
    - host: container.prd.jdwlabs.com

envs:
  ENVIRONMENT: prod
  AUTH_BASE_URL: https://usersrole.prd.jdwlabs.com
  SERVICE_DISCOVERY_BASE_URL: https://servicediscovery.prd.jdwlabs.com