image:
  tag: "2.1.22@sha256:2af633bd8c821fc679eb8d10135f5f0bf408f8c84f7d761aaa5a04e1f8cb91cb"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "160Mi"
    cpu: "500m"

ingress:
  hosts:
    - host: container.prd.jdwlabs.com

envs:
  ENVIRONMENT: prod
  AUTH_BASE_URL: https://usersrole.prd.jdwlabs.com
  SERVICE_DISCOVERY_BASE_URL: https://servicediscovery.prd.jdwlabs.com