revisionHistoryLimit: 1

ingress:
  hosts:
    - host: container.non.jdwlabs.com

envs:
  ENVIRONMENT: non
  AUTH_BASE_URL: https://usersrole.non.jdwlabs.com
  SERVICE_DISCOVERY_BASE_URL: https://servicediscovery.non.jdwlabs.com