image:
  tag: "2.1.17@sha256:402315e29c6381fe0fc83af6f1989bce9c99846e9db61ec58670d01e19b2f800"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "160Mi"
    cpu: "500m"

ingress:
  hosts:
    - host: container.prd.jdwlabs.com

envs:
  ENVIRONMENT: prod
  AUTH_BASE_URL: https://usersrole.prd.jdwlabs.com
  SERVICE_DISCOVERY_BASE_URL: https://servicediscovery.prd.jdwlabs.com