apps:
  # --- PRD environment ---
  - name: secret-store-prd
    namespace: jdwlabs-prd
    chartPath: charts/secret-store
    syncWave: "0"
    valueFiles:
      - values.yaml
      - values-prd.yaml

  - name: usersrole-prd
    namespace: jdwlabs-prd
    chartPath: charts/usersrole
    syncWave: "1"
    valueFiles:
      - values.yaml
      - values-prd.yaml

  - name: servicediscovery-prd
    namespace: jdwlabs-prd
    chartPath: charts/servicediscovery
    syncWave: "1"
    valueFiles:
      - values.yaml
      - values-prd.yaml

  - name: container-prd
    namespace: jdwlabs-prd
    chartPath: charts/container
    syncWave: "1"
    valueFiles:
      - values.yaml
      - values-prd.yaml

  - name: authui-prd
    namespace: jdwlabs-prd
    chartPath: charts/authui
    syncWave: "1"
    valueFiles:
      - values.yaml
      - values-prd.yaml

  - name: usersui-prd
    namespace: jdwlabs-prd
    chartPath: charts/usersui
    syncWave: "1"
    valueFiles:
      - values.yaml
      - values-prd.yaml

  - name: rolesui-prd
    namespace: jdwlabs-prd
    chartPath: charts/rolesui
    syncWave: "1"
    valueFiles:
      - values.yaml
      - values-prd.yaml
