image:
  tag: "2.0.4@sha256:29ca58911bf84d332b444f4fd81fbd7b1569b6226e1b3f9ac248123c6c28717f"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

ingress:
  hosts:
    - host: usersui.prd.jdwlabs.com

envs:
  ENVIRONMENT: prod
  AUTH_BASE_URL: https://usersrole.prd.jdwlabs.com