image:
  tag: "2.0.5@sha256:0fa68d736c7b275c2ee8a564a888265f3c20218fc69d04fdbe6b31ac55d0b90c"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

ingress:
  hosts:
    - host: usersui.prd.jdwlabs.com

envs:
  ENVIRONMENT: prod
  AUTH_BASE_URL: https://usersrole.prd.jdwlabs.com