image:
  tag: "2.0.2@sha256:04ab6179991fcda14aff8af2b11df8d39a1e472a1c654dd07f518bf7bed2d2e7"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

ingress:
  hosts:
    - host: usersui.prd.jdwlabs.com

envs:
  ENVIRONMENT: prod
  AUTH_BASE_URL: https://usersrole.prd.jdwlabs.com